import Database from 'better-sqlite3';
import { config } from '../config.js';

export class PremiumRepository {
  private db:any;
  constructor(path:string){this.db=new Database(path);this.db.exec(`CREATE TABLE IF NOT EXISTS premium_memberships (id INTEGER PRIMARY KEY, discord_user_id TEXT UNIQUE NOT NULL, stripe_customer_id TEXT, stripe_subscription_id TEXT, stripe_price_id TEXT, status TEXT NOT NULL, current_period_end TEXT, cancel_at_period_end INTEGER NOT NULL DEFAULT 0, access_source TEXT NOT NULL DEFAULT 'stripe', created_at TEXT NOT NULL, updated_at TEXT NOT NULL); CREATE INDEX IF NOT EXISTS premium_user_idx ON premium_memberships(discord_user_id); CREATE TABLE IF NOT EXISTS personal_chart_analyses (id INTEGER PRIMARY KEY, discord_user_id TEXT NOT NULL, symbol TEXT, timeframe TEXT, current_price TEXT, analysis_text TEXT NOT NULL, ai_model TEXT, created_at TEXT NOT NULL); CREATE INDEX IF NOT EXISTS analyses_user_idx ON personal_chart_analyses(discord_user_id,created_at);`)}
  membership(userId:string){return this.db.prepare('SELECT * FROM premium_memberships WHERE discord_user_id=?').get(userId) as any;}
  upsertStripe(userId:string, customerId:string|null, subscriptionId:string|null, priceId:string|null, status:string, periodEnd:string|null, cancelAtPeriodEnd:boolean){const now=new Date().toISOString();this.db.prepare(`INSERT INTO premium_memberships(discord_user_id,stripe_customer_id,stripe_subscription_id,stripe_price_id,status,current_period_end,cancel_at_period_end,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(discord_user_id) DO UPDATE SET stripe_customer_id=excluded.stripe_customer_id,stripe_subscription_id=excluded.stripe_subscription_id,stripe_price_id=excluded.stripe_price_id,status=excluded.status,current_period_end=excluded.current_period_end,cancel_at_period_end=excluded.cancel_at_period_end,updated_at=excluded.updated_at`).run(userId,customerId,subscriptionId,priceId,status,periodEnd,cancelAtPeriodEnd?1:0,now,now);}
  active(userId:string){const m=this.membership(userId);return Boolean(m && ['active','trialing','manual'].includes(m.status) && (!m.current_period_end || new Date(m.current_period_end)>new Date()));}
  canAnalyze(userId:string){const now=Date.now(), day=new Date(now-864e5).toISOString(), month=new Date(now-31*864e5).toISOString();const rows=this.db.prepare('SELECT created_at FROM personal_chart_analyses WHERE discord_user_id=? AND created_at>? ORDER BY created_at DESC').all(userId,month) as any[];if(rows.length>=config.premiumMonthlyLimit)return {ok:false,message:'You have reached your Premium AI analysis limit for this month.'};if(rows.filter(r=>r.created_at>day).length>=config.premiumDailyLimit)return {ok:false,message:'You have reached your Premium AI analysis limit for today.'};const last=rows[0]?.created_at?new Date(rows[0].created_at).getTime():0;const wait=config.premiumCooldownSeconds*1000-(now-last);return wait>0?{ok:false,message:`Please wait ${Math.ceil(wait/1000)} seconds before starting another analysis.`}:{ok:true,message:''};}
  saveAnalysis(userId:string,text:string){this.db.prepare('INSERT INTO personal_chart_analyses(discord_user_id,analysis_text,ai_model,created_at) VALUES (?,?,?,?)').run(userId,text,config.visionModel,new Date().toISOString());}
  history(userId:string){return this.db.prepare('SELECT id,symbol,timeframe,created_at FROM personal_chart_analyses WHERE discord_user_id=? ORDER BY id DESC LIMIT 10').all(userId) as any[];}
}
