import { EmbedBuilder, type Client } from 'discord.js';
import { config } from '../config.js';
import { MarketRepository } from './repository.js';
import { MarketSessionService } from './service.js';
const service=new MarketSessionService(); const fmt=(m:number)=>m<60?`${m}m`:`${Math.floor(m/60)}h ${m%60}m`;
export const marketsEmbed=()=>new EmbedBuilder().setColor(0x2b6cb0).setTitle('🌍 MARKET STATUS').setDescription(service.all().map(s=>`${s.session.emoji} **${s.session.name}**\n${s.open?'🟢 OPEN':'🔴 CLOSED'}\n${s.open?'Closes':'Opens'} in ${fmt(s.minutes)} • <t:${Math.floor(s.next.getTime()/1000)}:R>`).join('\n\n')).setFooter({text:'Display timezone: Eastern Time • General session information only'});
export const sessionsEmbed=()=>new EmbedBuilder().setColor(0x2b6cb0).setTitle('🌍 FOREX SESSIONS').setDescription(service.all().map(s=>`${s.session.emoji} **${s.session.name}**\nOpen: ${s.session.open}–${s.session.close} (${s.session.timezone})\nStatus: ${s.open?'🟢 OPEN':'🔴 CLOSED'}`).join('\n\n')).setFooter({text:'Eastern Time display; session locations automatically observe DST.'});
export const marketEmbed=(symbol:string)=>{const found=service.instrument(symbol); if(!found)return new EmbedBuilder().setColor(0xcc3333).setDescription(`No instrument profile for **${symbol.toUpperCase()}**.`);const {item,relevant}=found;const overlap=relevant.filter(s=>s.open);return new EmbedBuilder().setColor(0x2b6cb0).setTitle(`${item.emoji} ${item.label}`).setDescription(`${item.sessions.length?'General Market Status: '+(overlap.length?'🟢 ACTIVE SESSIONS':'🔴 NO RELEVANT SESSION OPEN'):'General Market Status: available by venue'}\n\nRelevant Sessions:\n${relevant.map(s=>`${s.session.emoji} ${s.session.name} — ${s.open?'OPEN':'CLOSED'}`).join('\n')||'No session mapping'}${overlap.length>1?'\n\nMajor overlap: '+overlap.map(s=>s.session.emoji+' '+s.session.name).join(' + '):''}${item.warning?'\n\n⚠️ '+item.warning:''}`)};
export function startMarketScheduler(client:Client, repo:MarketRepository){const run=async()=>{const channel=client.guilds.cache.get(config.guildId)?.channels.cache.find(c=>c.name==='market-alerts'&&c.isTextBased());if(!channel?.isTextBased()||!('send'in channel))return;for(const s of service.all()){const date=s.next.toISOString().slice(0,10);let type:string|undefined;if(s.open&&s.minutes===0)type='CLOSE';else if(!s.open&&[60,30,15].includes(s.minutes))type=`OPEN_${s.minutes}`;if(!type)continue;const key=`${s.session.id}_${date}_${type}`;if(repo.sent(key))continue;const text=type==='CLOSE'?`🔴 **MARKET CLOSED**\n${s.session.emoji} ${s.session.name} session is now closed.\nNext opening: <t:${Math.floor(s.next.getTime()/1000)}:F>`:`🔔 **MARKET ALERT**\n${s.session.emoji} **${s.session.name.toUpperCase()} SESSION**\nOpens in ${s.minutes} minutes.\n🕒 ${service.format(s.next)}\nMajor markets commonly active: ${s.session.instruments.join(', ')}`;await channel.send(text);repo.mark(key);}};void run();return setInterval(()=>void run(),60_000);}
