import { EmbedBuilder, type Client, type TextChannel } from 'discord.js';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { TradeLockerClient } from './client.js';
import type { TlOrder, TlPosition } from './types.js';

type Record = { orderId?: string; positionId?: string; messageId: string; channelId: string; status: string; entry?: number; stopLoss?: number; takeProfit?: number; volume?: number; symbol: string; side: string; updatedAt: string };
export class TradeSignalEngine {
  private records: Record[] = []; private running = false;
  constructor(private client: Client, private tl: TradeLockerClient, private file = './data/trade-signals.json') {}
  async init() { try { this.records = JSON.parse(await readFile(this.file, 'utf8')); } catch { this.records = []; } }
  private async save() { await mkdir(dirname(this.file), { recursive: true }); await writeFile(this.file, JSON.stringify(this.records, null, 2)); }
  private channel(name: string) { return this.client.guilds.cache.first()?.channels.cache.find(c => c.name === name && c.isTextBased()) as TextChannel | undefined; }
  private embed(title: string, item: TlOrder | TlPosition, status: string, extras: Array<{ name: string; value: string; inline?: boolean }> = []) { const entry = item.entry; const risk = entry && item.stopLoss ? Math.abs(entry - item.stopLoss) : undefined; const reward = entry && item.takeProfit ? Math.abs(item.takeProfit - entry) : undefined; const rr = risk && reward ? `1:${(reward / risk).toFixed(2)}` : '—'; return new EmbedBuilder().setColor(status.includes('LOSS') ? 0xe53e3e : status.includes('TP') ? 0x38a169 : status.includes('PENDING') ? 0xd69e2e : 0x3182ce).setTitle(title).addFields({ name: 'Market', value: item.symbol, inline: true }, { name: 'Direction', value: `${item.side}${'orderType' in item ? ` ${item.orderType}` : ''}`, inline: true }, { name: 'Entry', value: entry !== undefined ? String(entry) : '—', inline: true }, { name: 'Stop Loss', value: item.stopLoss !== undefined ? String(item.stopLoss) : '—', inline: true }, { name: 'Take Profit', value: item.takeProfit !== undefined ? String(item.takeProfit) : '—', inline: true }, { name: 'Risk/Reward', value: rr, inline: true }, { name: 'Volume', value: item.volume !== undefined ? String(item.volume) : '—', inline: true }, { name: 'Status', value: status, inline: true }, ...extras).setFooter({ text: 'Educational analysis only · Not financial advice · Outcomes are not guaranteed' }).setTimestamp(); }
  private find(item: TlOrder | TlPosition) { return this.records.find(r => r.orderId === ('orderId' in item ? item.orderId : item.openOrderId) || r.positionId === ('positionId' in item ? item.positionId : undefined)); }
  private async upsert(item: TlOrder | TlPosition, status: string, channelName: string, title: string, extras: Array<{ name: string; value: string; inline?: boolean }> = []) { const previous = this.find(item); const channel = this.channel(previous ? channelName : channelName); if (!channel) throw new Error(`Missing Discord channel #${channelName}`); const embed = this.embed(title, item, status, extras); if (previous) { const message = await channel.messages.fetch(previous.messageId).catch(() => undefined); if (message) await message.edit({ embeds: [embed] }); Object.assign(previous, { positionId: 'positionId' in item ? item.positionId : previous.positionId, status, updatedAt: new Date().toISOString() }); } else { const message = await channel.send({ embeds: [embed] }); this.records.push({ orderId: 'orderId' in item ? item.orderId : item.openOrderId, positionId: 'positionId' in item ? item.positionId : undefined, messageId: message.id, channelId: channel.id, status, entry: item.entry, stopLoss: item.stopLoss, takeProfit: item.takeProfit, volume: item.volume, symbol: item.symbol, side: item.side, updatedAt: new Date().toISOString() }); } await this.save(); }
  async reconcile() { if (!this.tl.enabled) return; const snapshot = await this.tl.snapshot(); for (const order of snapshot.orders) await this.upsert(order, ['PENDING', 'NEW'].some(state => order.status.includes(state)) ? '🟡 PENDING' : '🟢 ACTIVE', 'signals', '🚨 NEW TRADE SIGNAL'); for (const position of snapshot.positions) await this.upsert(position, '🟢 ACTIVE', 'signals', '🟢 TRADE ACTIVATED', [{ name: 'Position ID', value: position.positionId, inline: true }]); for (const order of snapshot.closedOrders.filter(o => o.status.includes('CANCEL'))) await this.upsert(order, '🚫 CANCELLED', 'signal-updates', '🚫 SIGNAL CANCELLED'); }
  start(seconds: number) { if (this.running || !this.tl.enabled) return; this.running = true; const tick = () => this.reconcile().catch(error => console.error('TradeLocker sync failed:', error.message)); tick(); setInterval(tick, Math.max(10, seconds) * 1000); }
}
