import { Client, Events, GatewayIntentBits, EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle } from 'discord.js';import { config, requireDiscordConfig } from './config.js';import { SignalStore } from './signals/store.js';import { handleSignal } from './commands/signals.js';import { ScreenshotSignalRepository } from './screenshot/repository.js';import { setupScreenshotWorkflow, updateStatus, authorized } from './screenshot/discord.js';import { MarketRepository } from './markets/repository.js';import { marketEmbed, marketsEmbed, sessionsEmbed, startMarketScheduler } from './markets/discord.js';import { LiveRepository } from './live/repository.js';import { refreshLiveMessage, setLiveStatus, staff, toggleLiveAlerts } from './live/discord.js';import { ObsService } from './live/obs.js';import { PremiumRepository } from './premium/repository.js';import { analyzeChart } from './premium/analyzer.js';import { createCheckout, startStripeWebhook } from './premium/stripe.js';requireDiscordConfig();const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMembers, GatewayIntentBits.GuildMessages, GatewayIntentBits.MessageContent] });const signals = new SignalStore();const screenshotSignals = new ScreenshotSignalRepository(config.databasePath);const marketRepo = new MarketRepository(config.databasePath);const liveRepo = new LiveRepository(config.databasePath);const obs = new ObsService();const premiumRepo = new PremiumRepository(config.databasePath);await signals.load();
async function premiumCheckoutReply(interaction: any) {
  try { const url = await createCheckout(interaction.user.id); return interaction.editReply({ content: '💎 **PREMIUM MEMBERSHIP**\nUnlock private educational chart analysis. Payment is handled securely by Stripe.', components: [new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setStyle(ButtonStyle.Link).setURL(url).setLabel('💎 GET PREMIUM'))] }); }
  catch (error) { console.error('Premium checkout creation failed:', error instanceof Error ? error.message : error); return interaction.editReply({ content: '⚠️ Premium checkout is temporarily unavailable. Please try again shortly.' }); }
}
async function ensurePremiumSignupPanel() {
  const guild = client.guilds.cache.get(config.guildId); const general = guild?.channels.cache.find(channel => channel.name === 'general' && channel.isTextBased()) as any; if (!general?.messages) return;
  const recent = await general.messages.fetch({ limit: 50 }); if (recent.find((message: any) => message.author.id === client.user?.id && message.embeds[0]?.title === 'Premium Membership')) return;
  const message = await general.send({ embeds: [new EmbedBuilder().setColor(0x2b6cb0).setTitle('Premium Membership').setDescription('Unlock Premium channels and private educational chart analysis.\n\n$25/week • Cancel through Stripe anytime\n\nSignals and analysis are educational only, not financial advice or guaranteed outcomes.')], components: [new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId('premium_join').setStyle(ButtonStyle.Primary).setLabel('Join Premium — $25/week'))] }); await message.pin().catch((error: Error) => console.error('Could not pin Premium signup panel:', error.message));
}
client.once(Events.ClientReady, ready => {  console.log(`Connected as ${ready.user.tag} for ${config.communityName}`); startMarketScheduler(client, marketRepo); startStripeWebhook(premiumRepo,client);  void refreshLiveMessage(client, liveRepo).catch(error => console.error('Live status refresh failed:', error.message));
  void ensurePremiumSignupPanel().catch(error => console.error('Premium signup panel failed:', error.message));  obs.start();});obs.onStreamChange = status => {  if (status === 'UNKNOWN') return;  void setLiveStatus(client, liveRepo, status, { notify: true }).catch(error => console.error('OBS live-state update failed:', error.message));};setupScreenshotWorkflow(client, screenshotSignals);client.on(Events.InteractionCreate, async interaction => { if (interaction.isButton() && interaction.customId === 'premium_join') { await interaction.deferReply({ ephemeral: true }); return void await premiumCheckoutReply(interaction); } if (!interaction.isChatInputCommand()) return;
